services:
  db:
    image: postgres:15
    container_name: rusttracker-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: rusttracker-backend
    depends_on:
      - db
    ports:
      - "${PORT}:8080"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      RUST_LOG: ${RUST_LOG:-info}
      PORT: 8080

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: rusttracker-frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      API_URL: http://backend:8080

volumes:
  postgres_data:
