name: Validate GitHub Secrets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1" # Every Monday at 8 AM UTC

jobs:
  validate-secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate required secrets exist
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          MAX_REQUESTS_PER_MINUTE: ${{ secrets.MAX_REQUESTS_PER_MINUTE }}
          RATE_LIMIT_WINDOW_MS: ${{ secrets.RATE_LIMIT_WINDOW_MS }}
        run: |
          echo "Checking required secrets..."

          # Check JWT_SECRET
          if [ -z "$JWT_SECRET" ]; then
            echo "ERROR: JWT_SECRET secret is missing"
            exit 1
          else
            echo "SUCCESS: JWT_SECRET secret exists"
            # Validate JWT secret length (should be at least 32 characters)
            if [ ${#JWT_SECRET} -lt 32 ]; then
              echo "WARNING: JWT_SECRET should be at least 32 characters long"
            fi
          fi

          # Check POSTGRES_PASSWORD
          if [ -z "$POSTGRES_PASSWORD" ]; then
            echo "ERROR: POSTGRES_PASSWORD secret is missing"
            exit 1
          else
            echo "SUCCESS: POSTGRES_PASSWORD secret exists"
          fi

          # Check optional secrets
          if [ -n "$POSTGRES_USER" ]; then
            echo "SUCCESS: POSTGRES_USER secret exists"
          else
            echo "INFO: POSTGRES_USER not set, will use default 'postgres'"
          fi

          if [ -n "$POSTGRES_DB" ]; then
            echo "SUCCESS: POSTGRES_DB secret exists"
          else
            echo "INFO: POSTGRES_DB not set, will use default 'rusttracker'"
          fi

          if [ -n "$MAX_REQUESTS_PER_MINUTE" ]; then
            echo "SUCCESS: MAX_REQUESTS_PER_MINUTE secret exists"
          else
            echo "INFO: MAX_REQUESTS_PER_MINUTE not set, will use default '100'"
          fi

          if [ -n "$RATE_LIMIT_WINDOW_MS" ]; then
            echo "SUCCESS: RATE_LIMIT_WINDOW_MS secret exists"
          else
            echo "INFO: RATE_LIMIT_WINDOW_MS not set, will use default '60000'"
          fi

          echo "SUCCESS: All required secrets validation passed"

      - name: Test environment creation
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          echo "Testing .env file creation with secrets..."
          cat > .env.test << EOF
          # Database configuration
          DATABASE_URL=postgresql://postgres:$POSTGRES_PASSWORD@db:5432/rusttracker
          POSTGRES_DB=rusttracker
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=$POSTGRES_PASSWORD
          POSTGRES_HOST=localhost
          POSTGRES_PORT=5432

          # Backend configuration
          RUST_LOG=info
          PORT=8080
          JWT_SECRET=$JWT_SECRET
          JWT_EXPIRY_HOURS=24

          # Frontend configuration
          FRONTEND_PORT=3000

          # Environment
          APP_ENV=production

          # Rate limiting settings
          MAX_REQUESTS_PER_MINUTE=100
          RATE_LIMIT_WINDOW_MS=60000
          EOF

          echo "SUCCESS: Environment file created successfully"
          echo "File size: $(wc -c < .env.test) bytes"

          # Clean up
          rm .env.test
